title: A Moonlit Cafe Press
description: A printer and distributer of tiny books.
base_url: https://moonlitcafe.co.uk

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: default
